# Generated by Django 5.2 on 2025-04-15 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmotionalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.TextField(max_length=500, verbose_name="Texto del usuario"),
                ),
                (
                    "emocion_primaria",
                    models.CharField(max_length=50, verbose_name="Emoción primaria"),
                ),
                (
                    "emocion_secundaria",
                    models.CharField(max_length=50, verbose_name="Emoción secundaria"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada Emocional",
                "verbose_name_plural": "Entradas Emocionales",
                "ordering": ["-fecha"],
            },
        ),
    ]
