# Generated by Django 5.2 on 2025-04-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionalentry",
            name="notas_revision",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas de revisión"
            ),
        ),
        migrations.AddField(
            model_name="emotionalentry",
            name="respuesta_correcta",
            field=models.BooleanField(
                default=True, verbose_name="¿Respuesta correcta?"
            ),
        ),
    ]
